version: '2'
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    build: .
    command: npm run devstart
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017/desafio
