version: '3'

volumes:
  mongo-data: {}

services:
  mongo:
    container_name: mongo
    #restart: always
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    container_name: server
    build: express_server
    command: npm run devstart
    volumes:
      - ./express_server:/usr/app
      - /usr/app/node_modules
    #restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017/desafio

  #app:
    #container_name: app
    #build: desafio_app
    #command: npm start
    #volumes:
      #- ./desafio_app:/usr/app
      #- /usr/app/node_modules
    #restart: always
    #ports:
      #- "4200:4200"
    #depends_on:
      #- server
    #environment:
      #API_URL: http://server:5000
